# Synology CSI Driver Helm values
# ref: https://github.com/SynologyOpenSource/synology-csi

clientInfoSecret: client-info-secret

storageClasses:
  - name: synology-iscsi-storage
    isDefault: true
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
    fsType: ext4
    dsm: 192.168.10.50  # Synology NAS (検証環境 VLAN 10)
    location: /volume1/k8s-pv

snapshotter:
  enabled: true
